export {default as Navbar} from './Navbar/Navbar'
export {default as Features} from './Features/Features'
export {default as Header} from './Header/Header'
export {default as Download} from './Download/Download'
export {default as Subscribe} from './Subscribe/Subscribe'
export {default as Faq} from './Faq/Faq'
export { default as Footer} from './Footer/Footer'